version: '3.4'

services:
  idttimeseri:
    image: ${DOCKER_REGISTRY-}idttimeseri
    container_name: paulwuapi
    ports: 
        - 7414:80
    environment:
     - redisserver=paulwuredistimeline:6379
    build:
      context: .
      dockerfile: IDTTimeseri/Dockerfile
    depends_on:
        - "redistimeline"

  redistimeline:
    image: paulwu/redistimeline:1.0
    container_name: paulwuredistimeline
    ports:
        - 6378:6379
networks:
    redisbackend:
        name: redisbackend
